[package]
name = "forktrace"
version = "0.1.0"
authors = ["Henry Harvey <hddharvey@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
log = "0.4.11"
slab = "0.4.2"
lazy_static = "1.4.0"
